#!/bin/sh

### BEGIN INIT INFO
# Provides:         kano-settings
# Required-Start:
# Required-Stop:
# X-Start-Before:   lightdm
# Default-Start:    2
# Default-Stop:
### END INIT INFO

# added welcome message

. /lib/lsb/init-functions

case "$1" in
    start)
	# Welcome message
        #echo "Microninja sta partendo..." > /dev/tty1

	log_action_begin_msg "Running microninja-settings-onboot"
	#/usr/bin/microninja-settings-onboot
	log_action_end_msg $?
	;;
    stop)
	;;
    restart|reload|force-reload|status)
        echo "Error: argument '$1' not supported" >&2
        exit 3
	;;
    *)
      echo "Usage: microninja-settings [start|stop]" >&2
      exit 3
      ;;
esac

